/**
 * pdfExport.js — ComplyRMG PDF generation engine
 * Uses jsPDF + jspdf-autotable (already in package.json)
 *
 * All functions return the jsPDF doc AND trigger a download.
 */
import jsPDF from 'jspdf'
import autoTable from 'jspdf-autotable'

// ── Design constants ──────────────────────────────────────────────────
const BRAND = {
  green:    [59, 130, 246],   // #3b82f6 blue
  greenDark:[29, 78, 216],    // #1d4ed8 dark blue for text on light
  dark:     [11, 15, 46],     // #0b0f2e deep navy
  mid:      [90, 110, 90],    // muted
  light:    [230, 240, 230],  // near-white green tint
  white:    [255, 255, 255],
  amber:    [251, 191, 36],
  red:      [248, 113, 113],
  border:   [220, 230, 220],
}

// ── Shared helpers ────────────────────────────────────────────────────

function newDoc() {
  return new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' })
}

/** Draw the ComplyRMG letterhead on a page */
function drawHeader(doc, { title, subtitle, pageLabel } = {}) {
  // Dark header bar
  doc.setFillColor(...BRAND.dark)
  doc.rect(0, 0, 210, 28, 'F')

  // Brand name
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(16)
  doc.setTextColor(...BRAND.green)
  doc.text('ComplyRMG', 14, 12)

  // Tagline
  doc.setFont('helvetica', 'normal')
  doc.setFontSize(7)
  doc.setTextColor(...BRAND.mid)
  doc.text('RMG COMPLIANCE PLATFORM · DHAKA, BANGLADESH', 14, 18)

  // Document type label (top right)
  if (pageLabel) {
    doc.setFont('helvetica', 'bold')
    doc.setFontSize(9)
    doc.setTextColor(...BRAND.green)
    doc.text(pageLabel, 196, 12, { align: 'right' })
  }

  // Title below header bar
  if (title) {
    doc.setFont('helvetica', 'bold')
    doc.setFontSize(18)
    doc.setTextColor(...BRAND.dark)
    doc.text(title, 14, 42)
  }
  if (subtitle) {
    doc.setFont('helvetica', 'normal')
    doc.setFontSize(9)
    doc.setTextColor(...BRAND.mid)
    doc.text(subtitle, 14, 49)
  }

  return 56 // y cursor after header block
}

/** Draw page footer with page number and generation date */
function drawFooter(doc) {
  const pageCount = doc.internal.getNumberOfPages()
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i)
    doc.setDrawColor(...BRAND.border)
    doc.setLineWidth(0.3)
    doc.line(14, 285, 196, 285)
    doc.setFont('helvetica', 'normal')
    doc.setFontSize(7)
    doc.setTextColor(...BRAND.mid)
    doc.text(`Generated by ComplyRMG · ${new Date().toLocaleDateString('en-GB')}`, 14, 290)
    doc.text(`Page ${i} of ${pageCount}`, 196, 290, { align: 'right' })
  }
}

/** Two-column key-value info block */
function infoBlock(doc, items, startY, colWidth = 88) {
  let y = startY
  const leftX = 14, rightX = 14 + colWidth + 8
  const pairs = []
  for (let i = 0; i < items.length; i += 2) {
    pairs.push([items[i], items[i + 1]])
  }
  pairs.forEach(([left, right]) => {
    if (left) {
      doc.setFont('helvetica', 'bold')
      doc.setFontSize(7)
      doc.setTextColor(...BRAND.mid)
      doc.text((left[0] || '').toUpperCase(), leftX, y)
      doc.setFont('helvetica', 'normal')
      doc.setFontSize(9)
      doc.setTextColor(...BRAND.dark)
      doc.text(String(left[1] || '—'), leftX, y + 4)
    }
    if (right) {
      doc.setFont('helvetica', 'bold')
      doc.setFontSize(7)
      doc.setTextColor(...BRAND.mid)
      doc.text((right[0] || '').toUpperCase(), rightX, y)
      doc.setFont('helvetica', 'normal')
      doc.setFontSize(9)
      doc.setTextColor(...BRAND.dark)
      doc.text(String(right[1] || '—'), rightX, y + 4)
    }
    y += 11
  })
  return y + 4
}

// ── INVOICE PDF ───────────────────────────────────────────────────────

/**
 * generateInvoicePDF(invoice, factory)
 * Produces a professional A4 invoice PDF.
 */
export function generateInvoicePDF(invoice, factory) {
  const doc = newDoc()
  let y = drawHeader(doc, { pageLabel: 'TAX INVOICE' })

  // Invoice title + number
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(22)
  doc.setTextColor(...BRAND.dark)
  doc.text('Invoice', 14, y + 4)

  doc.setFont('helvetica', 'normal')
  doc.setFontSize(10)
  doc.setTextColor(...BRAND.mid)
  doc.text(invoice.number, 196, y + 4, { align: 'right' })

  // Status badge
  const statusColors = { paid: BRAND.green, sent: BRAND.amber, draft: BRAND.mid, overdue: BRAND.red }
  const sc = statusColors[invoice.status] || BRAND.mid
  doc.setFillColor(...sc)
  doc.roundedRect(150, y - 2, 28, 8, 2, 2, 'F')
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(7)
  doc.setTextColor(...BRAND.white)
  doc.text(invoice.status.toUpperCase(), 164, y + 3.5, { align: 'center' })

  y += 14

  // Divider
  doc.setDrawColor(...BRAND.border)
  doc.setLineWidth(0.4)
  doc.line(14, y, 196, y)
  y += 8

  // Bill From / Bill To columns
  // From block
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(7)
  doc.setTextColor(...BRAND.mid)
  doc.text('FROM', 14, y)
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(10)
  doc.setTextColor(...BRAND.dark)
  doc.text('ComplyRMG', 14, y + 5)
  doc.setFont('helvetica', 'normal')
  doc.setFontSize(8.5)
  doc.setTextColor(...BRAND.mid)
  doc.text('Gulshan-2, Dhaka 1212, Bangladesh', 14, y + 10)
  doc.text('support@complyrm.com', 14, y + 15)
  doc.text('+880 1700 000000', 14, y + 20)

  // To block
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(7)
  doc.setTextColor(...BRAND.mid)
  doc.text('BILL TO', 110, y)
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(10)
  doc.setTextColor(...BRAND.dark)
  doc.text(factory?.name || invoice.factoryName, 110, y + 5)
  doc.setFont('helvetica', 'normal')
  doc.setFontSize(8.5)
  doc.setTextColor(...BRAND.mid)
  doc.text(factory?.location || '', 110, y + 10)
  doc.text(factory?.email || '', 110, y + 15)
  doc.text(factory?.phone || '', 110, y + 20)

  y += 30

  // Invoice meta row
  doc.setFillColor(...BRAND.light)
  doc.rect(14, y, 182, 14, 'F')
  const metaItems = [
    ['Invoice No', invoice.number],
    ['Issue Date', invoice.issueDate],
    ['Due Date',   invoice.dueDate],
    ['Period',     invoice.period],
  ]
  metaItems.forEach((item, idx) => {
    const x = 14 + idx * 46
    doc.setFont('helvetica', 'bold')
    doc.setFontSize(7)
    doc.setTextColor(...BRAND.mid)
    doc.text(item[0].toUpperCase(), x + 4, y + 5)
    doc.setFont('helvetica', 'bold')
    doc.setFontSize(8.5)
    doc.setTextColor(...BRAND.greenDark)
    doc.text(String(item[1] || ''), x + 4, y + 10)
  })
  y += 22

  // Line items table
  autoTable(doc, {
    startY: y,
    head: [['Description', 'Qty', 'Unit Price (৳)', 'Amount (৳)']],
    body: invoice.items.map(item => [
      item.description,
      String(item.qty),
      item.unitPrice.toLocaleString(),
      (item.qty * item.unitPrice).toLocaleString(),
    ]),
    theme: 'plain',
    headStyles: {
      fillColor: BRAND.dark,
      textColor: BRAND.green,
      fontSize: 8,
      fontStyle: 'bold',
      cellPadding: { top: 4, bottom: 4, left: 4, right: 4 },
    },
    bodyStyles: {
      fontSize: 9,
      textColor: BRAND.dark,
      cellPadding: { top: 5, bottom: 5, left: 4, right: 4 },
    },
    alternateRowStyles: { fillColor: [247, 252, 247] },
    columnStyles: {
      0: { cellWidth: 90 },
      1: { cellWidth: 20, halign: 'center' },
      2: { cellWidth: 36, halign: 'right' },
      3: { cellWidth: 36, halign: 'right', fontStyle: 'bold' },
    },
    margin: { left: 14, right: 14 },
  })

  y = doc.lastAutoTable.finalY + 6

  // Totals block (right-aligned)
  const subtotal = invoice.items.reduce((s, i) => s + i.qty * i.unitPrice, 0)
  const tax      = Math.round(subtotal * (invoice.taxRate || 0) / 100)
  const total    = subtotal + tax

  const totalsX = 130
  const totalsW = 66

  const totalsRows = [
    ['Subtotal', `৳${subtotal.toLocaleString()}`],
    ...(tax > 0 ? [[`VAT (${invoice.taxRate}%)`, `৳${tax.toLocaleString()}`]] : []),
    ['TOTAL DUE', `৳${total.toLocaleString()}`],
  ]

  totalsRows.forEach((row, ri) => {
    const isTotal = ri === totalsRows.length - 1
    const rowY    = y + ri * 9
    if (isTotal) {
      doc.setFillColor(...BRAND.dark)
      doc.rect(totalsX, rowY - 4, totalsW, 11, 'F')
      doc.setFont('helvetica', 'bold')
      doc.setFontSize(9)
      doc.setTextColor(...BRAND.green)
    } else {
      doc.setFont('helvetica', 'normal')
      doc.setFontSize(8.5)
      doc.setTextColor(...BRAND.mid)
    }
    doc.text(row[0], totalsX + 4, rowY + 2)
    doc.text(row[1], totalsX + totalsW - 4, rowY + 2, { align: 'right' })
  })

  y += totalsRows.length * 9 + 10

  // Payment instructions
  doc.setFillColor(...BRAND.light)
  doc.rect(14, y, 100, 38, 'F')
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(8)
  doc.setTextColor(...BRAND.greenDark)
  doc.text('Payment Instructions', 18, y + 7)
  doc.setFont('helvetica', 'normal')
  doc.setFontSize(7.5)
  doc.setTextColor(...BRAND.dark)
  const payLines = [
    'bKash Business: 01700-000000',
    'Bank: Dutch-Bangla Bank Ltd.',
    'A/C: 1234567890  |  Branch: Gulshan',
    'Routing: 090275654',
  ]
  payLines.forEach((line, i) => doc.text(line, 18, y + 14 + i * 5.5))

  // Notes
  if (invoice.notes) {
    doc.setFont('helvetica', 'bold')
    doc.setFontSize(7)
    doc.setTextColor(...BRAND.mid)
    doc.text('NOTES', 120, y + 7)
    doc.setFont('helvetica', 'normal')
    doc.setFontSize(8)
    doc.setTextColor(...BRAND.dark)
    const noteLines = doc.splitTextToSize(invoice.notes, 72)
    doc.text(noteLines, 120, y + 13)
  }

  y += 46

  // Signature line
  doc.setDrawColor(...BRAND.border)
  doc.setLineWidth(0.3)
  doc.line(14, y, 80, y)
  doc.setFont('helvetica', 'normal')
  doc.setFontSize(7)
  doc.setTextColor(...BRAND.mid)
  doc.text('Authorized Signature', 14, y + 4)
  doc.text('ComplyRMG', 14, y + 8)

  drawFooter(doc)
  doc.save(`${invoice.number}.pdf`)
  return doc
}

// ── WAGE REGISTER PDF ─────────────────────────────────────────────────

export function generateWageRegisterPDF({ workers, month, factory }) {
  const doc  = newDoc()
  const minW = 12500
  let y = drawHeader(doc, {
    title:     'Monthly Wage Register',
    subtitle:  `${month || 'Current Month'} · ${factory || 'Khaled Textiles Ltd.'}`,
    pageLabel: 'PAYROLL RECORD',
  })

  // Summary row
  const violations  = workers.filter(w => w.wage < minW).length
  const totalWage   = workers.reduce((s, w) => s + w.wage, 0)
  const totalOT     = workers.reduce((s, w) => s + (w.ot || 0), 0)
  const totalPayroll = totalWage + totalOT

  const summaryItems = [
    ['Workers', workers.length],
    ['Total Basic', `৳${totalWage.toLocaleString()}`],
    ['Total OT', `৳${totalOT.toLocaleString()}`],
    ['Total Payroll', `৳${totalPayroll.toLocaleString()}`],
    ['Violations', violations > 0 ? `${violations} BELOW MIN` : 'None'],
    ['Min Wage', '৳12,500 (Grade 7)'],
  ]

  doc.setFillColor(...BRAND.light)
  doc.rect(14, y, 182, 22, 'F')
  summaryItems.forEach((item, i) => {
    const col = i % 3
    const row = Math.floor(i / 3)
    const x   = 18 + col * 60
    const sy  = y + 6 + row * 10
    doc.setFont('helvetica', 'bold')
    doc.setFontSize(7)
    doc.setTextColor(...BRAND.mid)
    doc.text(String(item[0]).toUpperCase(), x, sy)
    doc.setFont('helvetica', 'bold')
    doc.setFontSize(9)
    doc.setTextColor(i === 4 && violations > 0 ? BRAND.red[0] : BRAND.greenDark[0], i === 4 && violations > 0 ? BRAND.red[1] : BRAND.greenDark[1], i === 4 && violations > 0 ? BRAND.red[2] : BRAND.greenDark[2])
    doc.text(String(item[1]), x, sy + 5)
  })
  y += 30

  // Main table
  autoTable(doc, {
    startY: y,
    head: [['Worker ID', 'Name', 'Dept', 'Grade', 'Basic Wage (৳)', 'Overtime (৳)', 'Total (৳)', 'Min Wage', 'Status']],
    body: workers.map(w => {
      const violation = w.wage < minW
      const ot = w.ot || 0
      return [
        w.id,
        w.name,
        w.dept,
        `Grade ${w.grade}`,
        w.wage.toLocaleString(),
        ot.toLocaleString(),
        (w.wage + ot).toLocaleString(),
        minW.toLocaleString(),
        violation ? 'VIOLATION' : 'OK',
      ]
    }),
    theme: 'plain',
    headStyles: {
      fillColor: BRAND.dark,
      textColor: BRAND.green,
      fontSize: 7,
      fontStyle: 'bold',
      cellPadding: { top: 3, bottom: 3, left: 3, right: 3 },
    },
    bodyStyles: { fontSize: 7.5, textColor: BRAND.dark, cellPadding: 3 },
    alternateRowStyles: { fillColor: [248, 253, 248] },
    columnStyles: {
      0: { cellWidth: 18 },
      1: { cellWidth: 38 },
      2: { cellWidth: 20 },
      3: { cellWidth: 16 },
      4: { cellWidth: 24, halign: 'right' },
      5: { cellWidth: 22, halign: 'right' },
      6: { cellWidth: 22, halign: 'right', fontStyle: 'bold' },
      7: { cellWidth: 18, halign: 'right' },
      8: { cellWidth: 18, halign: 'center' },
    },
    didParseCell: (data) => {
      if (data.section === 'body' && data.column.index === 8) {
        if (data.cell.raw === 'VIOLATION') {
          data.cell.styles.textColor = BRAND.red
          data.cell.styles.fontStyle = 'bold'
        } else {
          data.cell.styles.textColor = BRAND.green
        }
      }
    },
    margin: { left: 14, right: 14 },
  })

  // Signature row
  y = doc.lastAutoTable.finalY + 16
  const sigLines = [
    { label: 'Prepared by', x: 14 },
    { label: 'Verified by (HR Manager)', x: 80 },
    { label: 'Approved by (Factory Owner)', x: 146 },
  ]
  sigLines.forEach(({ label, x }) => {
    doc.setDrawColor(...BRAND.border)
    doc.setLineWidth(0.3)
    doc.line(x, y, x + 58, y)
    doc.setFont('helvetica', 'normal')
    doc.setFontSize(7)
    doc.setTextColor(...BRAND.mid)
    doc.text(label, x, y + 4)
  })

  drawFooter(doc)
  doc.save(`Wage-Register-${month || 'Current'}.pdf`)
  return doc
}

// ── WORKER RECORDS PDF ────────────────────────────────────────────────

export function generateWorkerRecordsPDF({ workers, factory }) {
  const doc = newDoc()
  let y = drawHeader(doc, {
    title:     'Worker Records',
    subtitle:  `NID Verified List · ${factory || 'Khaled Textiles Ltd.'}`,
    pageLabel: 'HR DOCUMENT',
  })

  const verified  = workers.filter(w => w.nid === 'verified').length
  const pending   = workers.filter(w => w.nid !== 'verified').length
  const violations = workers.filter(w => w.wage < 12500).length

  // Info strip
  infoBlock(doc, [
    ['Total Workers', workers.length],  ['NID Verified', verified],
    ['NID Pending',   pending],          ['Wage Violations', violations || 'None'],
    ['Generated',     new Date().toLocaleDateString('en-GB')], ['Audit Ready', verified === workers.length ? 'YES' : 'PARTIAL'],
  ], y)

  y += 40

  autoTable(doc, {
    startY: y,
    head: [['Worker ID', 'Name', 'Department', 'Grade', 'Monthly Wage', 'NID Status', 'Emp. Status', 'Date Joined']],
    body: workers.map(w => [
      w.id, w.name, w.dept, `Grade ${w.grade}`,
      `৳${w.wage.toLocaleString()}`,
      w.nid === 'verified' ? '✓ Verified' : 'Pending',
      w.status, w.joined,
    ]),
    theme: 'plain',
    headStyles: { fillColor: BRAND.dark, textColor: BRAND.green, fontSize: 7.5, fontStyle: 'bold', cellPadding: 3.5 },
    bodyStyles: { fontSize: 8, textColor: BRAND.dark, cellPadding: 3.5 },
    alternateRowStyles: { fillColor: [248, 253, 248] },
    didParseCell: (data) => {
      if (data.section === 'body' && data.column.index === 5) {
        data.cell.styles.textColor = data.cell.raw === '✓ Verified' ? BRAND.green : BRAND.amber
        data.cell.styles.fontStyle = 'bold'
      }
      if (data.section === 'body' && data.column.index === 4) {
        const wage = parseInt(data.cell.raw.replace(/[৳,]/g, ''))
        if (wage < 12500) data.cell.styles.textColor = BRAND.red
      }
    },
    margin: { left: 14, right: 14 },
  })

  drawFooter(doc)
  doc.save('Worker-Records.pdf')
  return doc
}

// ── INCIDENT LOG PDF ──────────────────────────────────────────────────

export function generateIncidentLogPDF({ incidents, factory }) {
  const doc = newDoc()
  let y = drawHeader(doc, {
    title:     'Incident & Accident Log',
    subtitle:  `BSCI Required Document · ${factory || 'Khaled Textiles Ltd.'}`,
    pageLabel: 'H&S RECORD',
  })

  const open     = incidents.filter(i => !i.resolved).length
  const resolved = incidents.filter(i => i.resolved).length

  infoBlock(doc, [
    ['Total Incidents', incidents.length], ['Open', open],
    ['Resolved',        resolved],          ['Period', `Up to ${new Date().toLocaleDateString('en-GB')}`],
  ], y)
  y += 26

  autoTable(doc, {
    startY: y,
    head: [['Date', 'Type', 'Location', 'Description', 'Corrective Action', 'Status']],
    body: incidents.map(i => [
      i.date, i.type, i.location,
      i.desc || '—',
      i.action || '—',
      i.resolved ? 'Resolved' : 'Open',
    ]),
    theme: 'plain',
    headStyles: { fillColor: BRAND.dark, textColor: BRAND.green, fontSize: 7.5, fontStyle: 'bold', cellPadding: 3.5 },
    bodyStyles: { fontSize: 7.5, textColor: BRAND.dark, cellPadding: 3.5 },
    alternateRowStyles: { fillColor: [248, 253, 248] },
    columnStyles: {
      0: { cellWidth: 20 },
      1: { cellWidth: 28 },
      2: { cellWidth: 30 },
      3: { cellWidth: 42 },
      4: { cellWidth: 42 },
      5: { cellWidth: 20, halign: 'center' },
    },
    didParseCell: (data) => {
      if (data.section === 'body' && data.column.index === 5) {
        data.cell.styles.textColor = data.cell.raw === 'Resolved' ? BRAND.green : BRAND.amber
        data.cell.styles.fontStyle = 'bold'
      }
    },
    margin: { left: 14, right: 14 },
  })

  drawFooter(doc)
  doc.save('Incident-Log.pdf')
  return doc
}

// ── AUDIT CHECKLIST PDF ───────────────────────────────────────────────

export function generateAuditChecklistPDF({ checklist, listType = 'BSCI', factory }) {
  const doc = newDoc()
  const allItems = checklist.flatMap(s => s.items)
  const done     = allItems.filter(i => i.checked).length
  const pct      = Math.round((done / allItems.length) * 100)

  let y = drawHeader(doc, {
    title:     `${listType} Audit Checklist`,
    subtitle:  `Readiness: ${pct}% · ${done}/${allItems.length} items complete · ${factory || 'Khaled Textiles Ltd.'}`,
    pageLabel: 'AUDIT PREP',
  })

  checklist.forEach((section) => {
    const secDone = section.items.filter(i => i.checked).length
    const secPct  = Math.round((secDone / section.items.length) * 100)

    autoTable(doc, {
      startY: y,
      head: [[{ content: `${section.section}   (${secDone}/${section.items.length} · ${secPct}%)`, colSpan: 3 }]],
      body: section.items.map(item => [
        item.checked ? '✓' : '○',
        item.text,
        item.tag,
      ]),
      theme: 'plain',
      headStyles: {
        fillColor: secPct === 100 ? BRAND.greenDark : secPct >= 60 ? [120, 90, 0] : [100, 30, 30],
        textColor: BRAND.white,
        fontSize: 8,
        fontStyle: 'bold',
        cellPadding: { top: 4, bottom: 4, left: 4, right: 4 },
      },
      bodyStyles: { fontSize: 7.5, textColor: BRAND.dark, cellPadding: 3 },
      alternateRowStyles: { fillColor: [248, 253, 248] },
      columnStyles: {
        0: { cellWidth: 10, halign: 'center', fontStyle: 'bold' },
        1: { cellWidth: 150 },
        2: { cellWidth: 22, halign: 'center', fontSize: 7, textColor: BRAND.mid },
      },
      didParseCell: (data) => {
        if (data.section === 'body' && data.column.index === 0) {
          data.cell.styles.textColor = data.cell.raw === '✓' ? BRAND.green : BRAND.border
          data.cell.styles.fontSize  = 10
        }
      },
      margin: { left: 14, right: 14 },
    })

    y = doc.lastAutoTable.finalY + 6
  })

  drawFooter(doc)
  doc.save(`${listType}-Checklist.pdf`)
  return doc
}
